### PR TITLE
gobenchdata@v1

### LINKED ISSUE #36: tracking issue: gobenchdata v1
If you use gobenchdata, I'd love to hear from you! Please feel free to respond to this issue or reach out to me at robert@bobheadxi.dev

> Previews are now available! See #38 for more details

## Won't Change

* benchmark storage format will stay the same - all existing run histories will work with v1 without a change
   * by extension, existing generated web apps will continue to work

### Improvements for CI Usage

**⚠️ to continue using the gobenchdata Action as-is when I release v1, you will need to pin your action version to `bobheadxi/gobenchdata@v0.5.1`**!

* [x] https://github.com/bobheadxi/gobenchdata/issues/28 and related output (check status? ~PR comments? generate image, a la https://github.com/bobheadxi/gobenchdata/issues/32?~)
    * at the moment my thinking is: all the output is available as JSON through some means, so advanced reports like PR comments and automated image generation+updates should be handled in separate actions (this one already does a lot as it is, since it includes the publishing mechanism)
* [x] More generic usage: allow pushing to different branches/repos
* [x] Follow GitHub Actions versioning conventions (i.e. use `bobheadxi/gobenchdata@v1`)

### Revamped Visualization

Better charts, more control over *what* gets charted (chart groups, more places to put descriptions, better ways to select groups of benchmarks)

* [x] https://github.com/bobheadxi/gobenchdata/issues/18
* [x] https://github.com/bobheadxi/gobenchdata/issues/15
* [x] investigate how multiple runs per day are rendered (https://github.com/bobheadxi/gobenchdata/issues/36#issuecomment-624363811)

### CLI improvements

* [x] https://github.com/bobheadxi/gobenchdata/issues/37

## Drafts

* [updated usage](https://github.com/bobheadxi/gobenchdata/compare/v1?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8)

### PR DESCRIPTION
**Pull request by bobheadxi**
closes #36 

GitHub tag (latest SemVer pre-release)

to try out the latest preview release:

```
git clone https://github.com/bobheadxi/gobenchdata.git
cd gobenchdata
git checkout v1
go install ./...
gobenchdata help
```

in your actions:

```yml
uses: bobheadxi/gobenchdata@v1
```

demo web apps:
* with configuration: https://bobheadxi.dev/gobenchdata-v1-demo/
* with minimal configuration: https://zapx.bobheadxi.dev/benchmarks/

known issues:

* [x] ~~irregular timeseries needs custom padding to have shared tooltips show up 😢 https://github.com/apexcharts/apexcharts.js/issues/420~~
* [x] ~~an explicit migration guide from `v0.5.x` will probably be helpful~~ - see Migrating section in release notes
* [x] ~~charts not visible on mobile~~
* [x] ~~x-axis is scaled to date, which looks pretty bad~~
* [ ] ApexCharts doesn't give a way to detect pans, so panning will always open the benchmark's commit on GitHub - I've opened an issue: apexcharts/apexcharts.js#1598
    * this can be circumvented by leaving out `repository` in `gobenchdata-web.yml`, but this will disable opening commits

remaining TODOs:

* [x] point demo actions to this repository's `gh-pages`
* [x] update `gh-pages` with the new web app

# Release Notes (wip)

[View Action](https://github.com/marketplace/actions/continuous-benchmarking-for-go) [Demo](https://gobenchdata.bobheadxi.dev/)

## :shipit: Improved Publishing

There are some breaking changes to the GitHub Action to improve publishing and enable checks.

* **⚠️ Breaking change** - `PUBLISH: true` must now be set to enable publishing
    * to continue using older versions of `gobenchdata` please pin your workflow to use `bobheadxi/gobenchdata@v0.5.1`!
* Publish results to any branch in any repository with `PUBLISH_REPO` and `PUBLISH_BRANCH` (just make sure `env.GITHUB_TOKEN` has the necessary permissions)
    * these are optional - the default behaviour remains the same (pushes to the host repository's `gh-pages` branch)

```yml
    - name: gobenchdata publish
      uses: bobheadxi/gobenchdata@v1
      with:
        PRUNE_COUNT: 30
        PUBLISH: true
        PUBLISH_REPO: bobheadxi/gobenchdata-v1-demo
        PUBLISH_BRANCH: master
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
```

## ✅ Checks

You can now define checks on benchmark results and check for regressions in pull requests.

* Configure checks with `gobenchdata-checks.yml` - get started with `gobenchdata checks generate`
    * define your own arithmetic for interpreting results - for example:
```yml
      diff: (current.NsPerOp-base.NsPerOp) / base.NsPerOp * 100
      thresholds:
            max: 10
```
* Run checks locally or in GitHub Actions
   * locally: `gobenchdata checks eval` - output can be output nicely with `--checks.pretty`, or saved with `--json`
       * JSON reports can be summarized with `gobenchdata checks report` 
   * in GitHub Actions:
```yml
    - name: gobenchdata checks
      uses: bobheadxi/gobenchdata@v1
      with:
        GO_TEST_FLAGS: -cpu 1,2
        CHECKS: true
        CHECKS_CONFIG: ./demo/gobenchdata-checks.yml
        PUBLISH_BRANCH: master
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
```

## 📉 New Web Application

The web application has been rewritten from the ground up!

* Now embedded in the core `gobenchdata` CLI
    * try it out with `gobenchdata web serve`!
    * generate a new app with `gobenchdata web generate ./app`
* Improved visualizations
    * charts are now built with [ApexCharts](https://apexcharts.com/), which brings built-in chart navigation, image generation, clearer tooltips, and more
* Improved configuration
    * define groups of charts, specify benchmarks and metrics to display, and include instructions for interpretation with the new `gobenchdata-web.yml` configuration format

image

### Existing Actions

```diff
- uses: bobheadxi/gobenchdata@v0.5.1
+ uses: bobheadxi/gobenchdata@v1
```

```diff
with:
+ PUBLISH: true
```

### Regenerating the Web App

Copy the title and description you are using to a temporary file. Delete `app.js`, `index.html`, `style.css`. Then:

```
go get -u go.bobheadxi.dev/gobenchdata
gobenchdata web generate . --web.title="My title"
```

Then, in `gobenchdata-web.yml`, add your description to the `description` field. Without configuring any `chartGroups`, the web app should generate similar charts to before - to start customizing, add some entries to `chartGroups`!

### CODE REVIEW

**Comment by bonedaddy** [comment]
Good work, one question since I use this in private repos and github doesn't really work so I have a somewhat convoluted setup. Which files do I store the benchmark results in? I have my previous benchmarks in `gobenchdata.json`, do I put these into the `chartGroups` section of `gobenchdata-web.yml` ?

**Comment by bonedaddy** [comment]
I'll use this comment to list whatever bugs I find while I test out on: https://rtradeltd.github.io/counter/

* When putting the benchmarks view into `panning` mode, if I try to click on the chart and pan it around it doesn't pan, and when I release my button click it [opens a new tab to this github repo](https://github.com/my/repository/commit/)

**Comment by bobheadxi** [comment]
> since I use this in private repos and github actions doesn't really work

Do you mind expanding on this a little? 😮 This should work anywhere, especially with the new `PUBLISH_REPO` and `PUBLISH_BRANCH` options - you could run the action on a private repo and push the results to a public one

> When putting the benchmarks view into panning mode, if I try to click on the chart and pan it around it doesn't pan, and when I release my button click it opens a new tab to this github repo

1. unfortunately it seems to be impossible to avoid the panning mode issue :/ I hook onto [`click`](https://apexcharts.com/docs/options/chart/events/) and ApexCharts doesn't give a way to detect pans - I've opened an issue: https://github.com/apexcharts/apexcharts.js/issues/1598
2. that github repo is configurable in `gobenchdata-web.yml` - it is used to link directly to the diff of a benchmark run:

```yml
title: gobenchdata web
description: Benchmarks generated using 'gobenchdata'
repository: https://github.com/bobheadxi/gobenchdata
```

**Comment by bobheadxi** [comment]
> https://rtradeltd.github.io/counter/

Noticed the charts here are pretty crowded - I've added an additional configuration option for charts to make them full-width (894b982):

```diff
chartGroups:
  - name: ...
    charts:
      - name: ...
+       display:
+         fullWidth: true
```

**Comment by leeoniya** [comment]
@bobheadxi 

in case you aren't married to Apex:

https://github.com/leeoniya/uPlot#performance

**Comment by bobheadxi** [comment]
@leeoniya thanks for the recommendation! unfortunately `uPlot` seems a little too barebones for my purposes (my choice of Apex was driven by a desire for some interactive functionality be taken care of out-of-the-box)

**Comment by leeoniya** [comment]
no problem :), there's a lot of options between Apex & uPlot tho, so food for thought...

**Comment by bobheadxi** [comment]
@leeoniya  I'd love to hear recommendations for libraries you prefer to Apex - I don't feel particularly strongly about it!  I checked out the list of libraries that uPlot is benchmarked against and nothing really struck my fancy, though I'd be happy to be convinced otherwise.

There are so many libraries, half of them unmaintained, some with too many features, some with too few... makes my head spin 😅

**Comment by leeoniya** [comment]
i only recommended uPlot because the only types of charts in your demo link [1] were timeseries. if you mostly need timeseries, my recommendation is still uPlot, since it does that and then-some. without knowing what you need it's impossible to recommend anything really. i'm also no expert in any of the libs in the bench.

i guess Chart.js v3 (alpha) would be a good starting point in terms of features, perf & lib size.

[1] https://bobheadxi.dev/gobenchdata-v1-demo/

**Comment by bobheadxi** [comment]
@bonedaddy if you don't have any other immediate issues, I think I'd like to get this out and address issues one by one :)

**Comment by bonedaddy** [comment]
> @bonedaddy if you don't have any other immediate issues, I think I'd like to get this out and address issues one by one :)

Sounds good to me, sorry for the delay. If you ever need a response from me "immediately" shoot me a DM on twitter I will notice that right away.

> Do you mind expanding on this a little? open_mouth This should work anywhere, especially with the new PUBLISH_REPO and PUBLISH_BRANCH options - you could run the action on a private repo and push the results to a public one

So this isn't an issue with gobenchdata, but an issue with github actions actually. Essentially it's possible, however AFAIK you need to copy the github actions into your private codebase. For example I could use `gobenchdata`, but I would have to clone the action into every single repository I want to use it in. https://github.community/t5/GitHub-Actions/Github-action-action-in-private-repository/td-p/29722 covers the problem. Unfortunately it doesn't look like it will be fixed anyimte soon :(


> unfortunately it seems to be impossible to avoid the panning mode issue :/ I hook onto click and ApexCharts doesn't give a way to detect pans - I've opened an issue

Ah goood to know.

> that github repo is configurable in gobenchdata-web.yml - it is used to link directly to the diff of a benchmark run
> I've updated the web app (d7d8615) to disable this behaviour if you leave the repository field blank, if you don't want it!

awesome, I will try this out.

> Noticed the charts here are pretty crowded - I've added an additional configuration option for charts to make them full-width (894b982):

awesome!!! :rocket:

**Comment by bobheadxi** [comment]
> So this isn't an issue with gobenchdata, but an issue with github actions actually. Essentially it's possible, however AFAIK you need to copy the github actions into your private codebase. For example I could use gobenchdata action, but I would have to clone the action into every single repository I want to use it in. https://github.community/t5/GitHub-Actions/Github-action-action-in-private-repository/td-p/29722 covers the problem. Unfortunately it doesn't look like it will be fixed anyimte soon :(

That's really interesting - I'll shot you a twitter DM regarding this!

**Pull request merged**
